CREATE TABLE IF NOT EXISTS pictures (
    id SERIAL PRIMARY KEY,
    profile_pic VARCHAR(255) NOT NULL,
    is_default BOOLEAN DEFAULT FALSE NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);